spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wechat?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource

  main:
    banner-mode: off
    #允许上传的最大文件大小
  servlet:
    multipart:
      max-file-size: 100MB

server:
  port: 80